### ISSUE TITLE
Web server GPL violation

### ISSUE THREAD

**Issue by shaiku** [cobyism/edimax-br-6528n#1]
I noticed you listed the web server webs as non-GPL according to Edimax.  I noticed, however, that webs is a modified version of the open-source Boa web server ( https://en.wikipedia.org/wiki/Boa_(web_server) ) which is licensed under GPLv2.  Edimax therefore needs to provide the source for their derivative work.

**Comment by cobyism** [comment]
👋 Hey there! Just in case it’s unclear, I have no affiliation or connection to Edimax, the ongoing maintenance of this codebase, or license issues their development team have, nor should this be considered the canonical home for this piece of software. I simply decided to mirror the source code Edimax made available via their website. Any issues identified with this code or associated licenses are things you should contact Edimax about directly.
